### PR TITLE
Interfaces/types for custom matchers intellisense

### LINKED ISSUE #6: VSCode intellisense does not work for custom matchers
### Expected behavior

Intellisense should work when using matchers in consumer unit tests.

### Actual behavior

The matchers do not show up in VSCode's autocomplete menu when typing.

### Steps to reproduce

Add this import to the top of a spec:

```
import { expect } from '@skyux-sdk/testing';
```

Type an expectation and wait for the autocomplete menu to appear. None of the SKY UX matchers show up:

screen shot 2018-12-06 at 9 21 41 am

### PR DESCRIPTION
**Pull request by Blackbaud-KrisMahon**
Fixes #6 

This includes strongly-typed and documented interface definitions for the custom Sky matchers.  Consumers can now enjoy intellisense for `expect` matchers.  No changes are needed for consumers.  I have tested locally in two different SPAs.  These new strongly-typed interfaces also highlighted that even some of the matchers and unit tests in this library were not written correctly because the original authors lacked the benefits of type safety.

### CODE REVIEW

File: src/app/public/matchers/matchers.ts [hunk 1]
```diff
@@ -124,7 +124,7 @@ const matchers: jasmine.CustomMatcherFactories = {
             }
 
             message.push(
-              `Expected element not to have CSS style "${styleName}: ${expectedStyle}"`
+              `Expected element did not have CSS style "${styleName}: ${expectedStyle}"`
```
Comment (Blackbaud-PaulCrowder) [inline src/app/public/matchers/matchers.ts:127]: This changes the meaning of the message. Its intent is to inform the caller that the specified element was expected to not have the specified CSS style, but it did have the specified style. The original message should be left intact.

Comment (Blackbaud-KrisMahon) [reply src/app/public/matchers/matchers.ts]: OK, I guess I misinterpreted this (and thought it was just poor wording) as I was trying to understand the code for writing the interface descriptions.  I changed it back.

File: src/app/public/matchers/matchers.spec.ts [hunk 2]
```diff
@@ -23,6 +23,7 @@ import 'rxjs/add/observable/of';
 import {
   expect
 } from './matchers';
+import { SkyA11yAnalyzerConfig } from '..';
```
Comment (Blackbaud-PaulCrowder) [inline src/app/public/matchers/matchers.spec.ts:26]: One other minor code style thing: This import should be multi-line and appear before the `import` before it since it's "farther away" than the import from a sibling file.

```
import { 
  SkyA11yAnalyzerConfig 
} from '..';

import {
  expect
} from './matchers';
```

Comment (Blackbaud-KrisMahon) [reply src/app/public/matchers/matchers.spec.ts]: Fixed and referenced the more specific `../a11y` import path.
